### PR TITLE
Setting `appVersion` for QML from `Version:` in spec-file

### PR DESCRIPTION
**Pull request by Olf0**

### CODE REVIEW

**Review by Olf0 — COMMENTED** [review]
This should cover all necessary changes, see https://github.com/search?q=repo%3Asailfishos-applications%2Ffilecase%20appVersion&type=code

P.S.: @dcaliste, I hope to have adopted your [FlowPlayer PR \#32](https://github.com/sailfishos-applications/flowplayer/pull/32) correctly and would appreciate a quick review of this PR very much.

**Review by dcaliste — APPROVED** [review]
This looks good to me. Didn't compile and try, but I cannot spot any misspell or wrongness.

**Comment by Olf0** [comment]
> This looks good to me.

Thank you very much!

> Didn't compile …

This aspect is taken care of by CI ([GitHub-workflow for each commit](https://github.com/sailfishos-applications/flowplayer/blob/devel/.github/workflows/build-on-pull_req.yml) to `devel`- and `master`-branch): It does compile.

> … and try …

Neither did I, but I simply define that as a job for the rc-testers. :wink:

**Comment by dcaliste** [comment]
Good, I didn't pay attention that the CI was checking the build. I did build for completeness myself a bit later after sending the feedback anyway ;-)

**Comment by Olf0** [comment]
> I did build for completeness myself …

Would it be helpful for you, if I let CI also build for aarch64@SFOS4.3.0 (runs on SFOS 4.4.0 & 4.5.0, too) for each commit to `devel`- and `master`-branch?  Or armv7hl@SFOS4.3.0, if that is appropriate for your testing device?

I currently only build for i486@SFOS3.0.2 as a compile test, because that downloads a much smaller SFOS-SDK Docker-image (~ 800 MB vs. 3 GB) and compiles faster than for armv7hl or aarch64 as target architecture.  Hence the current state is the quickest way to see, if the source code still compiles after a commit.

Only when setting a git-tag, the source code is compiled for all three architectures with multiple SFOS-SDK releases.

The results (i.e. RPM(s) and logs) of all these CI runs can be easily accessed by the [`Actions` tab](https://github.com/sailfishos-applications/filecase/actions) in GitHub's web-frontend.

**Comment by dcaliste** [comment]
Thanks for proposing. I think, it's currently fine as you set it up. I compile on the SDK, locally anyway for every change I make. And quickly test on device. Of course, I do this for the 4.5 target. So building with the simplest 3.0 for the CI, I think already provide a good hint on what could happen.

**Pull request merged**
